dependencies:
  - name: splunk-kubernetes-logging
    version: 1.1.0
    repository: stable
  - name: splunk-kubernetes-objects
    version: 1.1.0
    repository: stable
  - name: splunk-kubernetes-metrics
    version: 1.1.0
    repository: stable
